// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26/02/2025, 18:48:57
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/margr/Documents/GitHub/fluffy-journey/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/margr/Documents/GitHub/fluffy-journey/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/margr/Documents/GitHub/fluffy-journey/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/margr/Documents/GitHub/fluffy-journey/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/margr/Documents/GitHub/fluffy-journey/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/margr/Documents/GitHub/fluffy-journey/plugins/**/*.{js,ts,mjs}","C:/Users/margr/Documents/GitHub/fluffy-journey/composables/**/*.{js,ts,mjs}","C:/Users/margr/Documents/GitHub/fluffy-journey/utils/**/*.{js,ts,mjs}","C:/Users/margr/Documents/GitHub/fluffy-journey/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/margr/Documents/GitHub/fluffy-journey/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/margr/Documents/GitHub/fluffy-journey/app.config.{js,ts,mjs}","C:/Users/margr/Documents/GitHub/fluffy-journey/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;